name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # e.g., v0.1.0

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*


### Go to your GitHub repo

# Go to: Settings → Secrets and variables → Actions

# Click "New repository secret"

# Name it: PYPI_API_TOKEN

# Paste the token you copied from PyPI