name: Publish to PyPI
on:
  push:
    tags:
      - v*  # Trigger on any tag starting with 'v' (e.g., v0.1.18)
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install --upgrade build setuptools wheel
          pip install "numpy<2"  # Ensure NumPy compatibility
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}